version: '3.8'
services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
volumes:
  drupal_data:
